// <auto-generated />
using System;
using MakeBingo.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MakeBingo.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190205191803_Default")]
    partial class Default
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MakeBingo.Models.Board", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CellsStr");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("Link");

                    b.Property<string>("Maker");

                    b.Property<string>("ParentId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("MakeBingo.Models.Result", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BoardId");

                    b.Property<string>("CellsStr");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("MakeBingo.Models.Board", b =>
                {
                    b.HasOne("MakeBingo.Models.Board", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("MakeBingo.Models.Result", b =>
                {
                    b.HasOne("MakeBingo.Models.Board", "Board")
                        .WithMany("Results")
                        .HasForeignKey("BoardId");
                });
#pragma warning restore 612, 618
        }
    }
}
